### ISSUE TITLE
Retos vacios

### ISSUE THREAD

**Issue by andresmgsl** [enerfresio/enerdapp1#1]
Hola muy bien día, estoy viendo que enviaste el Reto pero en el repositorio no encuentro nada.. ¿Puedes porfa guiarme?. Gracias !

**Comment by enerfresio** [comment]
Hola, si lo envié por es erróneo... Estoy acabando de hacerlo y te lo
envío. Disculpa las molestias, como ya dije en el chat este es mi primer
curso de programación y voy muy lento. Sorry

**Comment by andresmgsl** [comment]
Nada que disculpar! Te agradezco tu aprticipación y aplaudo tus ganas de seguir! Voy a marcar este issue como cerrado y voy a proceder a revisar tu código!
